
services:
  
  back:
    container_name: budgeter_back
    image: budgeter-back
    build: back
    env_file:
      - path: back/.env
        required: true
    ports:
      - "8080:8080"
    networks:
      - budgeter-network

  front:
    container_name: budgeter_front
    image: budgeter-front
    build: front
    ports:
      - "80:80"
    networks:
      - budgeter-network
    depends_on:
      - back

networks:
  budgeter-network:
    driver: bridge
